version: "3"
services:
  thehive:
    image: strangebee/thehive:5.2
    depends_on:
      - cassandra
      # Remove cortex if not needed
      - cortex
    ports:
      - "9000:9010"
    environment:
      - JVM_OPTS="-Xms1024M -Xmx1024M"
      - SECRET_KEY="mySecretForTheHive"
      - "--cql-hostnames"
      - "cassandra"
      # Remove Elasticsearch related environment variables
      # - "--index-backend"
      # - "--es-hostnames"
      # Adjust S3 configuration if using external storage
      # ...
      
  cassandra:
    image: 'cassandra:4'
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=1024M
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - cassandradata:/var/lib/cassandra
    restart: on-failure

# Remove minio service definition

  cortex:
    image: thehiveproject/cortex:3.1.7
    environment:
      - job_directory=/tmp/cortex-jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cortex-jobs:/tmp/cortex-jobs
    ports:
      - "9001:9011"

volumes:
  cassandradata:
